blueprint:
  name: ILG Werktijd bijhouden met pauze timeout
  description: |
    Houdt je werktijd bij op basis van aanwezigheid in een zone met pauze timeout.
    Stuurt notificaties na 8 uur aanwezigheid en wekelijks totaal.
    Zet begin en eindtijd in een kalender.
    Handmatige starttijd aanpassing mogelijk.
    Ondersteunt twee notificatie ontvangers.
  domain: automation
  input:
    telefoon:
      name: Telefoon device tracker
      description: Device tracker entiteit van je telefoon
      selector:
        entity:
          domain: device_tracker
    werkzone:
      name: Werk zone
      description: Zone waar je werkdag begint en eindigt
      selector:
        entity:
          domain: zone
    pauze_timeout:
      name: Pauze timeout (minuten)
      description: Hoe lang mag je maximaal buiten de zone zijn voordat je werkdag stopt
      default: 30
      selector:
        number:
          min: 1
          max: 180
          unit_of_measurement: minutes
          mode: slider
    notificatie_1:
      name: Eerste notificatie ontvanger
      description: Eerste notificatie service (bijv notify.mobile_app)
      selector:
        action: {}
    notificatie_2:
      name: Tweede notificatie ontvanger (optioneel)
      description: Tweede notificatie service, kan leeg blijven
      default: ''
      selector:
        action: {}
    kalender:
      name: Kalender om werkuren in te zetten
      description: Kalender waar begin- en eindtijden worden opgeslagen
      selector:
        entity:
          domain: calendar
    weektotaal_helper:
      name: Helper voor weektotaal uren (input_number)
      description: Helper om totaal gewerkte uren per week bij te houden
      selector:
        entity:
          domain: input_number
    werkdag_duur:
      name: Standaard werkdag duur (uren)
      description: Aantal uren dat je normaal werkt per dag (voor notificatie grens)
      default: 8.5
      selector:
        number:
          min: 1
          max: 24
          unit_of_measurement: hours

variables:
  telefoon: !input telefoon
  werkzone: !input werkzone
  pauze_timeout: !input pauze_timeout
  notificatie_1: !input notificatie_1
  notificatie_2: !input notificatie_2
  kalender: !input kalender
  weektotaal_helper: !input weektotaal_helper
  werkdag_duur: !input werkdag_duur

trigger:
  - platform: state
    entity_id: !input telefoon

condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input telefoon
            state: 'home'
            for: 
              minutes: 1
        sequence:
          # Als je telefoon in werkzone is
          - wait_for_trigger:
              - platform: state
                entity_id: !input telefoon
                to: 'not_home'
          - delay:
              minutes: 0
          - choose:
              - conditions:
                  - condition: state
                    entity_id: input_boolean.ilg_werktijd_actief
                    state: 'off'
                sequence:
                  - service: input_boolean.turn_on
                    target:
                      entity_id: input_boolean.ilg_werktijd_actief
                  - service: input_datetime.set_datetime
                    target:
                      entity_id: input_datetime.ilg_werktijd_start
                    data:
                      datetime: "{{ now().isoformat() }}"
                  - service: calendar.create_event
                    data:
                      calendar_id: "{{ kalender }}"
                      summary: "Werkdag start"
                      start: "{{ now().isoformat() }}"
                      end: "{{ (now() + timedelta(minutes=1)).isoformat() }}"
              - default: []
          - delay:
              minutes: "{{ pauze_timeout }}"
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input telefoon
                    state: 'not_home'
                    for:
                      minutes: "{{ pauze_timeout }}"
                sequence:
                  - service: input_boolean.turn_off
                    target:
                      entity_id: input_boolean.ilg_werktijd_actief
                  - service: input_datetime.set_datetime
                    target:
                      entity_id: input_datetime.ilg_werktijd_einde
                    data:
                      datetime: "{{ now().isoformat() }}"
                  - service: calendar.create_event
                    data:
                      calendar_id: "{{ kalender }}"
                      summary: "Werkdag einde"
                      start: "{{ now().isoformat() }}"
                      end: "{{ (now() + timedelta(minutes=1)).isoformat() }}"
                  - service: input_number.set_value
                    data:
                      entity_id: "{{ weektotaal_helper }}"
                      value: >
                        {% set start = state_attr('input_datetime.ilg_werktijd_start', 'timestamp') %}
                        {% set einde = now().timestamp() %}
                        {% if start %}
                          {{ ((einde - start) / 3600) | round(2) }}
                        {% else %}
                          0
                        {% endif %}
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ ((now() - state_attr('input_datetime.ilg_werktijd_start', 'timestamp')|default(0)) / 3600) >= werkdag_duur }}"
                        sequence:
                          - service: notify.notify
                            target:
                              entity_id: "{{ notificatie_1 }}"
                            data:
                              message: "Je werkdag is bijna voorbij!"
                          - choose:
                              - conditions:
                                  - condition: template
                                    value_template: "{{ notificatie_2 != '' }}"
                                sequence:
                                  - service: notify.notify
                                    target:
                                      entity_id: "{{ notificatie_2 }}"
                                    data:
                                      message: "Je werkdag is bijna voorbij!"
                      - default: []
              - default: []
      - conditions:
          - condition: state
            entity_id: !input telefoon
            state: 'not_home'
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.ilg_werktijd_actief
          - service: input_datetime.set_datetime
            target:
              entity_id: input_datetime.ilg_werktijd_einde
            data:
              datetime: "{{ now().isoformat() }}"
          - service: calendar.create_event
            data:
              calendar_id: "{{ kalender }}"
              summary: "Werkdag einde"
              start: "{{ now().isoformat() }}"
              end: "{{ (now() + timedelta(minutes=1)).isoformat() }}"
          - service: input_number.set_value
            data:
              entity_id: "{{ weektotaal_helper }}"
              value: >
                {% set start = state_attr('input_datetime.ilg_werktijd_start', 'timestamp') %}
                {% set einde = now().timestamp() %}
                {% if start %}
                  {{ ((einde - start) / 3600) | round(2) }}
                {% else %}
                  0
                {% endif %}
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ ((now() - state_attr('input_datetime.ilg_werktijd_start', 'timestamp')|default(0)) / 3600) >= werkdag_duur }}"
                sequence:
                  - service: notify.notify
                    target:
                      entity_id: "{{ notificatie_1 }}"
                    data:
                      message: "Je werkdag is bijna voorbij!"
                  - choose:
                      - conditions:
                          - condition: template
                            value_template: "{{ notificatie_2 != '' }}"
                        sequence:
                          - service: notify.notify
                            target:
                              entity_id: "{{ notificatie_2 }}"
                            data:
                              message: "Je werkdag is bijna voorbij!"
              - default: []
    default: []

mode: single

