blueprint:
  name: ILG Werktijd Tracking
  description: Houdt werktijden bij op basis van aanwezigheid in een zone met pauzetimer, notificaties, weektotaal en kalendernotities.
  domain: automation
  input:
    telefoon:
      name: Telefoon entity (device_tracker)
      description: Kies je telefoon device_tracker entity.
      selector:
        entity:
          domain: device_tracker

    werk_zone:
      name: Werkzone
      description: Zone die je werkplek representeert.
      selector:
        entity:
          domain: zone

    notificatie_1:
      name: Hoofd notificatie ontvanger
      description: Eerste notificatie kanaal.
      selector:
        action: {}

    notificatie_2:
      name: Tweede notificatie ontvanger (optioneel)
      description: Tweede notificatie kanaal, leeg laten als niet gebruikt.
      default: null
      selector:
        action: {}

    calendar_werktijden:
      name: Kalender om werktijden in te noteren
      description: Kalender entity waarin begin- en eindtijden worden bijgehouden.
      selector:
        entity:
          domain: calendar

    pauze_timeout_minuten:
      name: Pauze timeout (minuten)
      description: Hoe lang mag je buiten de werkzone zijn zonder werkdag te beëindigen.
      default: 30
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: minutes

variables:
  telefoon: !input telefoon
  werk_zone: !input werk_zone
  notif1: !input notificatie_1
  notif2: !input notificatie_2
  kalender: !input calendar_werktijden
  pauze_timeout: !input pauze_timeout_minuten

trigger:
  - platform: state
    entity_id: !input telefoon
  - platform: time
    at: '17:15:00'

action:
  - choose:
      # Start werkdag als telefoon binnen zone komt en werkdag nog niet actief is
      - conditions:
          - condition: state
            entity_id: !input telefoon
            state: 'home'
          - condition: state
            entity_id: input_boolean.ilg_werkdag_actief
            state: 'off'
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.ilg_werkdag_actief
          - service: input_datetime.set_datetime
            target:
              entity_id: input_datetime.ilg_werkdag_starttijd
            data:
              timestamp: "{{ now().timestamp() }}"
          - service: calendar.event_create
            data:
              calendar_id: "{{ kalender }}"
              start: "{{ now().isoformat() }}"
              end: "{{ (now() + timedelta(minutes=30)).isoformat() }}"
              summary: "Werkdag start"
          - service: input_number.set_value
            target:
              entity_id: input_number.ilg_uur_totaal_dag
            data:
              value: 0

      # Telefoon verlaat zone, start pauzetimer
      - conditions:
          - condition: state
            entity_id: !input telefoon
            state: 'not_home'
          - condition: state
            entity_id: input_boolean.ilg_werkdag_actief
            state: 'on'
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: !input telefoon
                to: 'home'
            timeout: "{{ pauze_timeout * 60 }}"
            continue_on_timeout: true
          - choose:
              # Pauze langer dan timeout, einde werkdag
              - conditions:
                  - condition: state
                    entity_id: !input telefoon
                    state: 'not_home'
                sequence:
                  - service: input_boolean.turn_off
                    target:
                      entity_id: input_boolean.ilg_werkdag_actief
                  - service: input_datetime.set_datetime
                    target:
                      entity_id: input_datetime.ilg_werkdag_eindtijd
                    data:
                      timestamp: "{{ now().timestamp() }}"
                  - service: calendar.event_create
                    data:
                      calendar_id: "{{ kalender }}"
                      start: "{{ states('input_datetime.ilg_werkdag_starttijd') }}"
                      end: "{{ now().isoformat() }}"
                      summary: "Werkdag einde"
                  - variables:
                      dag_uren: "{{ ((as_timestamp(now()) - as_timestamp(states('input_datetime.ilg_werkdag_starttijd'))) / 3600) | round(2) }}"
                  - service: input_number.set_value
                    target:
                      entity_id: input_number.ilg_uur_totaal_dag
                    data:
                      value: "{{ dag_uren }}"
                  - service: input_number.set_value
                    target:
                      entity_id: input_number.ilg_uur_totaal_week
                    data:
                      value: "{{ (states('input_number.ilg_uur_totaal_week') | float) + dag_uren }}"
                  - service: notify.notify
                    data:
                      message: "Je werkdag is beëindigd. Duur: {{ dag_uren }} uur."
                      target:
                        - "{{ notif1 }}"
                        - "{{ notif2 }}"

      # Notificatie na 8 uur aanwezigheid
      - conditions:
          - condition: state
            entity_id: input_boolean.ilg_werkdag_actief
            state: 'on'
          - condition: template
            value_template: >
              {{ (as_timestamp(now()) - as_timestamp(states('input_datetime.ilg_werkdag_starttijd'))) > (8 * 3600) }}
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          - service: notify.notify
            data:
              message: "Je bent al 8 uur aan het werk. Je werkdag zit er bijna op!"
              target:
                - "{{ notif1 }}"
                - "{{ notif2 }}"

      # Wekelijkse samenvatting vrijdag 17:15
      - conditions:
          - condition: time
            weekday:
              - fri
          - condition: time
            at: '17:15:00'
        sequence:
          - service: notify.notify
            data:
              message: "Deze week heb je in totaal {{ states('input_number.ilg_uur_totaal_week') }} uur gewerkt."
              target:
                - "{{ notif1 }}"
                - "{{ notif2 }}"
          - service: input_number.set_value
            target:
              entity_id: input_number.ilg_uur_totaal_week
            data:
              value: 0
    default: []

mode: single
