blueprint:
  name: ILG - Werktijdregistratie met zone en notificaties
  description: Houdt werktijd bij op basis van zone. Stuurt meldingen, registreert agenda-items en houdt weektotaal bij.
  domain: automation
  input:
    telefoon:
      name: Telefoon (person entity)
      selector:
        entity:
          domain: person

    zone:
      name: Werkzone
      selector:
        entity:
          domain: zone

    calendar:
      name: Werktijd kalender
      selector:
        entity:
          domain: calendar

    notify_1:
      name: Eerste notificatie ontvanger
      description: Entity ID van eerste notify-ontvanger (bijv. notify.mobile_app_elmer)
      selector:
        text:

    notify_2:
      name: Tweede notificatie ontvanger (optioneel)
      default: ""
      selector:
        text:

    weektotaal_helper:
      name: Helper - ILG Weektotaal
      selector:
        entity:
          domain: input_number

    actief_helper:
      name: Helper - Werktijd actief
      selector:
        entity:
          domain: input_boolean

    start_helper:
      name: Helper - Werktijd start
      selector:
        entity:
          domain: input_datetime

    einde_helper:
      name: Helper - Werktijd einde
      selector:
        entity:
          domain: input_datetime

    pauze_timeout:
      name: Pauze timeout in minuten
      description: Tijd waarin een afwezigheid géén einde werkdag betekent
      default: 30
      selector:
        number:
          min: 1
          max: 180
          unit_of_measurement: minuten
          mode: slider

    notificatie_uur:
      name: Notificatie na 8 uur?
      default: true
      selector:
        boolean:

trigger:
  - platform: state
    entity_id: !input telefoon
    to: "home"
  - platform: state
    entity_id: !input telefoon
    to: "not_home"
  - platform: time
    at: "17:15:00"
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input telefoon
            state: "home"
          - condition: state
            entity_id: !input actief_helper
            state: "off"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: !input actief_helper
          - service: input_datetime.set_datetime
            target:
              entity_id: !input start_helper
            data:
              timestamp: "{{ now().timestamp() }}"
          - service: notify.notify
            data:
              message: "Werkdag gestart."
              target: [!input notify_1, !input notify_2]
      - conditions:
          - condition: state
            entity_id: !input telefoon
            state: "not_home"
          - condition: state
            entity_id: !input actief_helper
            state: "on"
          - condition: template
            value_template: >
              {{ (now().timestamp() - (states[inputs.telefoon].last_changed | as_timestamp)) > (inputs.pauze_timeout * 60) }}
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: !input actief_helper
          - service: input_datetime.set_datetime
            target:
              entity_id: !input einde_helper
            data:
              timestamp: "{{ now().timestamp() }}"
          - variables:
              start: "{{ states[inputs.start_helper].state | as_datetime }}"
              einde: "{{ now() }}"
              duur: "{{ (einde - start).total_seconds() / 3600 | round(2) }}"
          - service: input_number.set_value
            target:
              entity_id: !input weektotaal_helper
            data:
              value: >
                {{ (states[inputs.weektotaal_helper].state | float(0)) + duur }}
          - service: calendar.create_event
            data:
              entity_id: !input calendar
              start: "{{ start.isoformat() }}"
              end: "{{ einde.isoformat() }}"
              summary: "Werktijd ({{ duur }} uur)"
          - service: notify.notify
            data:
              message: "Werkdag geëindigd. Totaal vandaag: {{ duur }} uur"
              target: [!input notify_1, !input notify_2]
      - conditions:
          - condition: time
            weekday:
              - fri
          - condition: template
            value_template: "{{ now().hour == 17 and now().minute == 15 }}"
        sequence:
          - service: notify.notify
            data:
              message: "Weekoverzicht: totaal gewerkt: {{ states[inputs.weektotaal_helper].state }} uur"
              target: [!input notify_1, !input notify_2]
  - choose:
      - conditions:
          - condition: state
            entity_id: !input actief_helper
            state: "on"
          - condition: template
            value_template: >
              {{ now() >= (states[inputs.start_helper].state | as_datetime + timedelta(hours=8)) }}
          - condition: template
            value_template: >
              {{ inputs.notificatie_uur }}
        sequence:
          - service: notify.notify
            data:
              message: "Je bent al 8 uur aan het werk. Bijna tijd om af te sluiten."
              target: [!input notify_1, !input notify_2]
mode: single

