blueprint:
  name: ILG Werktijden bijhouden met pauze timeout en notificaties (handmatige notify input)
  description: >
    Houdt je werkuren bij op basis van aanwezigheid in een zone met pauze timeout.
    Stuurt notificaties na 8 uur en op vrijdag totaal, en schrijft begin en eindtijden in calendar.
  domain: automation
  input:
    telefoon:
      name: Telefoon entity
      description: De device_tracker of person entity van je telefoon
      selector:
        entity:
          domain: device_tracker
    werkzone:
      name: Werkzone
      description: Zone waar je telefoon moet zijn om te registreren als werken
      selector:
        entity:
          domain: zone
    kalender:
      name: Werktijden kalender
      description: Kalender waarin begin- en eindtijd worden opgeslagen
      selector:
        entity:
          domain: calendar
    pauze_timeout:
      name: Pauze timeout (minuten)
      description: Tijd in minuten waarna verlaten zone als einde werkdag wordt gezien (pauze)
      default: 30
      selector:
        number:
          min: 1
          max: 180
          unit_of_measurement: minutes
    notificatie_1:
      name: Eerste notificatie ontvanger
      description: Vul hier je notificatie entiteit in, bijvoorbeeld notify.mobile_app_elmer
      selector:
        text:
    notificatie_2:
      name: Tweede notificatie ontvanger (optioneel)
      description: Vul hier een tweede notificatie entiteit in, of laat leeg
      default: ""
      selector:
        text:
    werktijd_helper:
      name: Helper voor weektotaal werktijd (in seconden)
      description: Helper die het totaal aantal gewerkte seconden per week bijhoudt
      selector:
        entity:
          domain: input_number
    begintijd_helper:
      name: Handmatige begintijd helper
      description: Helper voor handmatig aanpassen van begintijd (optie)
      selector:
        entity:
          domain: input_datetime

variables:
  telefoon: !input telefoon
  werkzone: !input werkzone
  kalender: !input kalender
  pauze_timeout: !input pauze_timeout
  notificatie_1: !input notificatie_1
  notificatie_2: !input notificatie_2
  werktijd_helper: !input werktijd_helper
  begintijd_helper: !input begintijd_helper

trigger:
  - platform: state
    entity_id: !input telefoon
  - platform: time
    at: "17:15:00"
    weekday:
      - fri

condition: []

action:
  - choose:
      # Start werkdag als telefoon zone betreedt op een werkdag
      - conditions:
          - condition: state
            entity_id: "{{ telefoon }}"
            state: "home"
          - condition: state
            entity_id: "{{ werkzone }}"
            state: "home"
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          - service: calendar.create_event
            data:
              calendar_id: "{{ kalender }}"
              start: "{{ now().isoformat() }}"
              end: "{{ (now() + timedelta(hours=8, minutes=30)).isoformat() }}"
              summary: "Werkdag start"
          - service: input_datetime.set_datetime
            data:
              entity_id: "{{ begintijd_helper }}"
              datetime: "{{ now().isoformat() }}"
          - service: input_number.set_value
            data:
              entity_id: "{{ werktijd_helper }}"
              value: 0
          - service: notify.notify
            data:
              message: "Werkdag gestart"
  - choose:
      # Einde werkdag na verlaten zone langer dan pauze_timeout (alleen werkdagen)
      - conditions:
          - condition: state
            entity_id: "{{ telefoon }}"
            state: "not_home"
          - condition: template
            value_template: >
              {{ (now() - states[telefoon].last_changed).total_seconds() > (pauze_timeout * 60) }}
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          - service: calendar.create_event
            data:
              calendar_id: "{{ kalender }}"
              start: "{{ states[begintijd_helper].state }}"
              end: "{{ now().isoformat() }}"
              summary: "Werkdag einde"
          - service: notify.notify
            data:
              message: "Werkdag afgesloten"
  - choose:
      # Notificatie na 8 uur werken
      - conditions:
          - condition: template
            value_template: >
              {{ (now() - states[begintijd_helper].state | as_datetime).total_seconds() >= 8 * 3600 }}
          - condition: state
            entity_id: "{{ telefoon }}"
            state: "home"
          - condition: state
            entity_id: "{{ werkzone }}"
            state: "home"
        sequence:
          - service: notify.service
            data:
              message: "Je werkdag is bijna voorbij (8 uur gewerkt)."
              target: 
                - "{{ notificatie_1 }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notificatie_2 != '' }}"
                sequence:
                  - service: notify.service
                    data:
                      message: "Je werkdag is bijna voorbij (8 uur gewerkt)."
                      target:
                        - "{{ notificatie_2 }}"
  - choose:
      # Wekelijkse notificatie vrijdag 17:15 met totaal gewerkte uren
      - conditions:
          - condition: time
            at: "17:15:00"
          - condition: state
            entity_id: "{{ werktijd_helper }}"
        sequence:
          - service: notify.service
            data:
              message: >
                Je hebt deze week {{ (states[werktijd_helper].state | float / 3600) | round(2) }} uur gewerkt.
              target:
                - "{{ notificatie_1 }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ notificatie_2 != '' }}"
                sequence:
                  - service: notify.service
                    data:
                      message: >
                        Je hebt deze week {{ (states[werktijd_helper].state | float / 3600) | round(2) }} uur gewerkt.
                      target:
                        - "{{ notificatie_2 }}"
          - service: input_number.set_value
            data:
              entity_id: "{{ werktijd_helper }}"
              value: 0
