blueprint:
  name: ILG Werktijd bijhouden met pauze timeout en notificaties
  description: >
    Track je werktijden op basis van aanwezigheid in zone.ilg_enschede.
    Met pauze timeout, notificaties na 8 uur, begin- en eindtijd in kalender,
    mogelijkheid om starttijd handmatig aan te passen, en twee notificatie ontvangers.
  domain: automation
  input:
    telefoon:
      name: Telefoon device tracker
      description: Je telefoon als device tracker entity
      selector:
        entity:
          domain: device_tracker

    werkzone:
      name: Werk zone
      description: De zone die aangeeft dat je aan het werk bent
      default: zone.ilg_enschede
      selector:
        entity:
          domain: zone

    pauze_timeout:
      name: Pauze timeout (minuten)
      description: Tijd in minuten dat je buiten de werkzone kunt zijn zonder dat de werkdag stopt
      default: 30
      selector:
        number:
          min: 1
          max: 180
          unit_of_measurement: minutes
          mode: slider

    werktijd_dag:
      name: Standaard werktijd per dag (uur)
      description: Het aantal uren dat je normaal werkt per dag
      default: 8.5
      selector:
        number:
          min: 1
          max: 24
          unit_of_measurement: hours
          mode: box

    notificatie_1:
      name: Eerste notificatie ontvanger
      description: Kies een notificatie entiteit (bijv notify.mobile_app_elmer)
      selector:
        entity:
          domain: notify

    notificatie_2:
      name: Tweede notificatie ontvanger (optioneel)
      description: Tweede notificatie entiteit, kan leeg blijven
      default: ''
      selector:
        entity:
          domain: notify

    calendar_werktijden:
      name: Kalender voor werktijden
      description: Kalender waarin begin- en eindtijden worden opgeslagen
      default: calendar.werktijden
      selector:
        entity:
          domain: calendar

    weektotaal_helper:
      name: Helper voor weektotaal werktijd (uren)
      description: Helper sensor (input_number) waarin het totaal van de week wordt bijgehouden
      selector:
        entity:
          domain: input_number

    handmatige_starttijd_helper:
      name: Handmatige starttijd helper (input_datetime)
      description: Helper om handmatig starttijd van de werkdag te corrigeren
      selector:
        entity:
          domain: input_datetime

variables:
  telefoon: !input telefoon
  werkzone: !input werkzone
  pauze_timeout_min: !input pauze_timeout
  werktijd_per_dag: !input werktijd_dag
  notificatie_1: !input notificatie_1
  notificatie_2: !input notificatie_2
  calendar_werktijden: !input calendar_werktijden
  weektotaal_helper: !input weektotaal_helper
  handmatige_starttijd_helper: !input handmatige_starttijd_helper

trigger:
  - platform: state
    entity_id: !input telefoon
  - platform: time
    at: "17:15:00"
    weekday:
      - fri

condition:
  - condition: or
    conditions:
      - condition: template
        value_template: >
          {{ is_state(trigger.entity_id, 'home') and
             is_state_attr(werkzone, 'friendly_name', 'ilg_enschede') }}
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri

action:
  - choose:
      - conditions:
          - condition: trigger
            id: "telefoon_in_werkzone"
          - condition: state
            entity_id: "{{ telefoon }}"
            state: "home"
          - condition: state
            entity_id: "{{ werkzone }}"
            state: "home"
        sequence:
          - variables:
              starttijd: >
                {% set manual = states(handmatige_starttijd_helper) %}
                {% if manual and manual != 'unavailable' and manual != 'unknown' %}
                  {{ manual }}
                {% else %}
                  {{ now().isoformat() }}
                {% endif %}
          - service: calendar.create_event
            data:
              calendar_id: "{{ calendar_werktijden }}"
              summary: Werkdag gestart
              start: "{{ starttijd }}"
              end: "{{ starttijd }}"
          - service: input_boolean.turn_on
            entity_id: input_boolean.ILG_werkdag_actief
          - service: notify.notify
            data:
              message: "Werkdag gestart om {{ starttijd }}"

      - conditions:
          - condition: trigger
            id: "telefoon_verlaat_werkzone"
          - condition: state
            entity_id: "{{ telefoon }}"
            state_not: "home"
          - condition: state
            entity_id: "{{ werkzone }}"
            state_not: "home"
        sequence:
          - delay: "00:{{ pauze_timeout_min }}:00"
          - condition: state
            entity_id: "{{ telefoon }}"
            state_not: "home"
          - service: calendar.create_event
            data:
              calendar_id: "{{ calendar_werktijden }}"
              summary: Werkdag beëindigd
              start: "{{ now().isoformat() }}"
              end: "{{ now().isoformat() }}"
          - service: input_boolean.turn_off
            entity_id: input_boolean.ILG_werkdag_actief
          - service: notify.notify
            data:
              message: "Werkdag beëindigd om {{ now().strftime('%H:%M') }}"

      - conditions:
          - condition: trigger
            platform: time
            at: "17:15:00"
            weekday:
              - fri
        sequence:
          - service: notify.notify
            data:
              message: >
                Totaal uren gewerkt deze week: {{
                states(weektotaal_helper) }} uur.

    default: []

mode: single
