blueprint:
  name: ILG Werktijd Tracking met Pauze en Notificaties
  description: >
    Track je werktijd op basis van aanwezigheid in een zone.
    Houd pauzes bij met een instelbare timeout.
    Stuur notificaties na 8 uur en wekelijks een overzicht.
    Maak agenda items aan voor begin- en eindtijd en dagtotaal.
    Inclusief handmatige starttijd aanpassing en 2 notificatieontvangers.
  domain: automation
  input:
    telefoon:
      name: Telefoon entity (device_tracker)
      description: Kies je telefoon device_tracker entity.
      selector:
        entity:
          domain: device_tracker

    werkzone:
      name: Werkzone
      description: Zone waarin je werk wordt geteld.
      selector:
        entity:
          domain: zone

    pauze_timeout:
      name: Pauze timeout (minuten)
      description: Tijd dat je buiten de werkzone kan zijn zonder werkdag te beëindigen.
      default: 30
      selector:
        number:
          min: 1
          max: 180
          unit_of_measurement: minutes
          mode: box

    notificatie_1:
      name: Eerste notificatie ontvanger
      description: Eerste device of service om notificaties na 8 uur te ontvangen.
      selector:
        target:

    notificatie_2:
      name: Tweede notificatie ontvanger (optioneel)
      description: Tweede ontvanger voor notificaties (optioneel).
      selector:
        target:
      default: []

    kalender:
      name: Kalender entity
      description: Kalender om werkdag begin- en eindtijden te noteren.
      selector:
        entity:
          domain: calendar

    week_helper:
      name: Helper voor weektotaal uren
      description: Helper (input_number) om de uren per week bij te houden.
      selector:
        entity:
          domain: input_number

    werkdag_duur:
      name: Standaard werkdag duur (uren)
      description: Tijdsduur van een normale werkdag.
      default: 8.5
      selector:
        number:
          min: 1
          max: 24
          unit_of_measurement: hours
          mode: box

variables:
  telefoon: !input telefoon
  werkzone: !input werkzone
  pauze_timeout: !input pauze_timeout
  notificatie_1: !input notificatie_1
  notificatie_2: !input notificatie_2
  kalender: !input kalender
  week_helper: !input week_helper
  werkdag_duur: !input werkdag_duur

trigger:
  - platform: state
    entity_id: !input telefoon
    to: 'home'    # Telefoon komt in de zone (home betekent aanwezig in jouw zone)
  - platform: state
    entity_id: !input telefoon
    from: 'home'
    to: 'not_home'  # Telefoon verlaat zone
  - platform: time
    at: '17:15:00'  # Elke vrijdag notificatie

condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri

action:
  - choose:
      # Begin werkdag: telefoon komt in zone
      - conditions:
          - condition: trigger
            id: 'trigger_in_zone'
          - condition: state
            entity_id: !input telefoon
            state: 'home'
          - condition: template
            value_template: >
              {{ not is_state('input_boolean.ilg_werktijd_actief', 'on') }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.ilg_werktijd_actief
          - service: input_datetime.set_datetime
            target:
              entity_id: input_datetime.ilg_werktijd_start
            data:
              timestamp: "{{ now().timestamp() }}"
          - service: calendar.create_event
            data:
              calendar_id: "{{ kalender }}"
              start: "{{ now().isoformat() }}"
              end: "{{ (now() + timedelta(hours=werkdag_duur)).isoformat() }}"
              summary: "Werkdag Start"
          - service: notify.notify
            data:
              target: !input notificatie_1
              message: "Werktijd gestart om {{ now().strftime('%H:%M') }}."
          - service: notify.notify
            data:
              target: !input notificatie_2
              message: "Werktijd gestart om {{ now().strftime('%H:%M') }}."
          - wait_for_trigger:
              - platform: state
                entity_id: !input telefoon
                to: 'not_home'
            continue_on_timeout: true
            timeout: "{{ (pauze_timeout * 60) | int }}" # pauze timeout in seconden
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input telefoon
                    state: 'not_home'
                    for: "{{ (pauze_timeout * 60) | int }}s"
                sequence:
                  # Werkdag beeindigen na timeout
                  - service: input_boolean.turn_off
                    target:
                      entity_id: input_boolean.ilg_werktijd_actief
                  - service: input_datetime.set_datetime
                    target:
                      entity_id: input_datetime.ilg_werktijd_einde
                    data:
                      timestamp: "{{ now().timestamp() }}"
                  - service: calendar.create_event
                    data:
                      calendar_id: "{{ kalender }}"
                      start: "{{ states('input_datetime.ilg_werktijd_start') }}"
                      end: "{{ now().isoformat() }}"
                      summary: "Werkdag Eind"
                  - service: input_number.set_value
                    target:
                      entity_id: "{{ week_helper }}"
                    data:
                      value: >
                        {{ (states('input_number.' + week_helper.split('.')[1])|float + 
                        ((as_timestamp(now()) - as_timestamp(states('input_datetime.ilg_werktijd_start'))) / 3600))|round(2) }}
                  - service: notify.notify
                    data:
                      target: !input notificatie_1
                      message: "Werkdag beëindigd om {{ now().strftime('%H:%M') }}."
                  - service: notify.notify
                    data:
                      target: !input notificatie_2
                      message: "Werkdag beëindigd om {{ now().strftime('%H:%M') }}."
              - default:
                  # Telefoon terug binnen pauze, werkdag gaat door
                  - service: notify.notify
                    data:
                      target: !input notificatie_1
                      message: "Pauze onderbroken, werktijd gaat door."
                  - service: notify.notify
                    data:
                      target: !input notificatie_2
                      message: "Pauze onderbroken, werktijd gaat door."

      # Na 8 uur notificatie (kan aangepast worden)
      - conditions:
          - condition: template
            value_template: >
              {{ is_state('input_boolean.ilg_werktijd_actief', 'on') and
                 (as_timestamp(now()) - as_timestamp(states('input_datetime.ilg_werktijd_start'))) > (8 * 3600) }}
        sequence:
          - service: notify.notify
            data:
              target: !input notificatie_1
              message: "Let op, je bent al meer dan 8 uur aan het werk."
          - service: notify.notify
            data:
              target: !input notificatie_2
              message: "Let op, je bent al meer dan 8 uur aan het werk."

      # Wekelijkse samenvatting op vrijdag 17:15
      - conditions:
          - condition: time
            weekday:
              - fri
            after: '17:14:00'
            before: '17:16:00'
        sequence:
          - service: notify.notify
            data:
              target: !input notificatie_1
              message: >
                "Wekelijkse werktijd totaal: {{ states(week_helper) }} uur."
          - service: notify.notify
            data:
              target: !input notificatie_2
              message: >
                "Wekelijkse werktijd totaal: {{ states(week_helper) }} uur."
          - service: input_number.set_value
            target:
              entity_id: "{{ week_helper }}"
            data:
              value: 0

mode: restart
