blueprint:
  name: ILG – Werkuren bijhouden compleet
  description: Houdt werktijd bij op basis van zone met pauze‑timeout, weekrapport, handmatige starttijd, en 8‑uur melding.
  domain: automation
  input:
    telefoon:
      name: Telefoon device tracker
      selector:
        entity:
          domain: device_tracker
    werkzone:
      name: Werkzone
      selector:
        entity:
          domain: zone
    notificatie:
      name: Notificatie service
      selector:
        action
    kalender:
      name: Werkuren kalender
      selector:
        entity:
          domain: calendar
    pauze_timeout:
      name: Pauze timeout (minuten)
      default: 30
      selector:
        number:
          min: 1
          max: 180
          unit_of_measurement: minuten
    handmatige_starttijd:
      name: Starttijd handmatig (optioneel)
      selector:
        entity:
          domain: input_datetime
    notif_8u_boolean:
      name: Boolean voor 8‑uur notificatie
      selector:
        entity:
          domain: input_boolean

variables:
  telefoon_id: !input telefoon
  werkzone_id: !input werkzone
  notificatie_service: !input notificatie
  kalender_id: !input kalender
  pauze_timeout_value: !input pauze_timeout
  handmatige_start_id: !input handmatige_starttijd
  notif_8u_id: !input notif_8u_boolean

trigger:
  - platform: state
    entity_id: "{{ telefoon_id }}"
  - platform: time_pattern
    minutes: '/5'
  - platform: time
    at: '17:15:00'
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri

condition: []

action:
  - choose:
      - conditions:
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
          - condition: template
            value_template: "{{ trigger.platform == 'time' }}"
        sequence:
          - service: "{{ notificatie_service }}"
            data:
              message: >
                Weektotaal gewerkte uren: {{
                  states('input_number.werktijd_totaal_week') | float | round(2)
                }} uur.
          - service: input_number.set_value
            data:
              entity_id: input_number.werktijd_totaal_week
              value: 0

      - conditions:
          - condition: state
            entity_id: "{{ telefoon_id }}"
            state: 'home'
          - condition: template
            value_template: "{{ trigger.platform != 'time' }}"
        sequence:
          - service: input_number.set_value
            data:
              entity_id: input_number.werktijd_vandaag
              value: 0
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ notif_8u_id }}"
          - service: "{{ notificatie_service }}"
            data:
              message: "Werkdag gestart."

      - conditions:
          - condition: state
            entity_id: "{{ telefoon_id }}"
            state: 'not_home'
          - condition: template
            value_template: "{{ trigger.platform != 'time' }}"
        sequence:
          - wait_for_trigger:
              - platform: state
                entity_id: "{{ telefoon_id }}"
                to: 'home'
            timeout: "{{ (pauze_timeout_value * 60) | int }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ wait.trigger is none }}"
                sequence:
                  - service: script.ilg_einde_werkdag
                    data:
                      telefoon: "{{ telefoon_id }}"
                      kalender: "{{ kalender_id }}"
                      notificatie: "{{ notificatie_service }}"
                      handmatige_starttijd: "{{ handmatige_start_id }}"
              - default:
                  - service: "{{ notificatie_service }}"
                    data:
                      message: "Terug binnen pauze, werkdag loopt door."

      - default:
          - condition: state
            entity_id: "{{ telefoon_id }}"
            state: 'home'
          - service: input_number.increment
            data:
              entity_id: input_number.werktijd_vandaag
              amount: 0.0833

      - conditions:
          - condition: state
            entity_id: "{{ telefoon_id }}"
            state: 'home'
          - condition: numeric_state
            entity_id: input_number.werktijd_vandaag
            above: 8
          - condition: state
            entity_id: "{{ notif_8u_id }}"
            state: 'off'
        sequence:
          - service: "{{ notificatie_service }}"
            data:
              message: "Je bent nu 8 uur op werk, bijna klaar voor vandaag!"
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ notif_8u_id }}"

mode: single
