blueprint:
  name: ILG Werktijd Tracker
  description: Houd werktijden bij op basis van aanwezigheid in zone.ilg_enschede met pauze timeout en notificaties.
  domain: automation
  input:
    telefoon:
      name: Telefoon device tracker
      description: Device tracker van je telefoon
      selector:
        entity:
          domain: device_tracker
    werkzone:
      name: Werkzone
      description: Zone waarin je werkt
      default: zone.ilg_enschede
      selector:
        entity:
          domain: zone
    kalender:
      name: Kalender voor werkdag events
      description: Kalender waarin werkdag begint en eindigt worden geregistreerd
      selector:
        entity:
          domain: calendar
    notificatie:
      name: Notificatie ontvanger 1
      description: Eerste notificatie service
      selector:
        action: {}
    notificatie_2:
      name: Notificatie ontvanger 2 (optioneel)
      description: Tweede notificatie service (leeg als niet gebruikt)
      default: ''
      selector:
        action: {}
    pauze_timeout:
      name: Pauze timeout (minuten)
      description: Max tijd afwezig in zone zonder dat werkdag stopt
      default: 30
      selector:
        number:
          min: 1
          max: 120
          unit_of_measurement: min
          mode: box
    werktijd_vandaag:
      name: Helper voor werktijd vandaag
      description: Input_number helper om vandaag gewerkte uren bij te houden
      selector:
        entity:
          domain: input_number
    werktijd_totaal_week:
      name: Helper voor werktijd totaal week
      description: Input_number helper om weektotaal uren bij te houden
      selector:
        entity:
          domain: input_number
    notif_8u:
      name: Helper boolean voor 8u notificatie verstuurd
      description: Input_boolean helper die bijhoudt of 8u notificatie is verstuurd
      selector:
        entity:
          domain: input_boolean
    handmatige_starttijd:
      name: Handmatige starttijd (optioneel)
      description: Input_datetime helper om starttijd handmatig te zetten
      selector:
        entity:
          domain: input_datetime

variables:
  telefoon: !input telefoon
  werkzone: !input werkzone
  kalender: !input kalender
  notificatie: !input notificatie
  notificatie_2: !input notificatie_2
  pauze_timeout: !input pauze_timeout
  werktijd_vandaag: !input werktijd_vandaag
  werktijd_totaal_week: !input werktijd_totaal_week
  notif_8u: !input notif_8u
  handmatige_starttijd: !input handmatige_starttijd

trigger:
  - platform: state
    entity_id: !input telefoon
    from: 'not_home'
    to: !input werkzone
  - platform: state
    entity_id: !input telefoon
    from: !input werkzone
    to: 'not_home'
  - platform: time
    at: '17:15:00'
  - platform: time_pattern
    minutes: /1

condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input telefoon
            state: !input werkzone
        sequence:
          - variables:
              starttijd: >
                {% if states(handmatige_starttijd) not in ['unknown','unavailable',''] and states(handmatige_starttijd) %}
                  {{ states(handmatige_starttijd) }}
                {% else %}
                  {{ state_attr(telefoon, 'last_updated') }}
                {% endif %}
              laatste_verlaten: >
                {% set last_left = state_attr(telefoon, 'last_changed') %}
                {{ last_left }}
          - service: input_datetime.set_datetime
            target:
              entity_id: handmatige_starttijd
            data:
              timestamp: "{{ now().timestamp() }}"
          - service: input_number.set_value
            target:
              entity_id: werktijd_vandaag
            data:
              value: 0
          - service: input_boolean.turn_off
            target:
              entity_id: notif_8u

      - conditions:
          - condition: state
            entity_id: !input telefoon
            state: 'not_home'
        sequence:
          - delay: "00:{{ '%02d' | format(pauze_timeout) }}:00"
          - condition: state
            entity_id: !input telefoon
            state: 'not_home'
          - variables:
              starttijd: >
                {% if states(handmatige_starttijd) not in ['unknown','unavailable',''] and states(handmatige_starttijd) %}
                  {{ states(handmatige_starttijd) }}
                {% else %}
                  {{ state_attr(telefoon, 'last_updated') }}
                {% endif %}
              eindtijd: "{{ now().isoformat() }}"
              duur_uren: >
                {% set start = as_timestamp(starttijd) %}
                {% set einde = as_timestamp(now()) %}
                {{ ((einde - start) / 3600) | round(2) }}
          - service: script.ilg_einde_werkdag
            data:
              telefoon: telefoon
              kalender: kalender
              notificatie: notificatie
              notificatie_2: notificatie_2
              handmatige_starttijd: handmatige_starttijd
              duur_uren: duur_uren

      - conditions:
          - condition: time
            at: '17:15:00'
        sequence:
          - service: notify.mobile_app_elmer
            data:
              message: >
                De totaal gewerkte uren deze week zijn {{ states(werktijd_totaal_week) }} uur.

      - conditions:
          - condition: state
            entity_id: !input telefoon
            state: !input werkzone
        sequence:
          - service: input_number.set_value
            target:
              entity_id: werktijd_vandaag
            data:
              value: >
                {% set start = as_timestamp(states(handmatige_starttijd)) if states(handmatige_starttijd) not in ['unknown','unavailable',''] else as_timestamp(state_attr(telefoon, 'last_updated')) %}
                {% set nu = as_timestamp(now()) %}
                {{ ((nu - start) / 3600) | round(2) }}
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: werktijd_vandaag
                    above: 8
                  - condition: state
                    entity_id: notif_8u
                    state: 'off'
                sequence:
                  - service: notify.mobile_app_elmer
                    data:
                      message: "Je werkdag duurt al meer dan 8 uur."
                  - service: input_boolean.turn_on
                    target:
                      entity_id: notif_8u
  default: []
